BusStationIS/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BusStationIS.Data.Models.Weather;
using BusStationIS.Data.ServiceSpecification;
using BusStationIS.Models;
using BusStationIS.Models.City;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Tables;

namespace BusStationIS.Controllers
{
    public class CityController : Controller
    {
        private readonly ICity _cityService;
        private readonly IBusStation _busStationService;
        private readonly ICarrier _carrierService;

        public CityController(ICity cityService,IBusStation busStationService,ICarrier carrierService)
        {
            _cityService = cityService;
            _busStationService = busStationService;
            _carrierService = carrierService;
        }
        public IActionResult Index()
        {
            var citys = _cityService.GetAll();

            var cityListing = citys.Select(c => new CityDetailModel
            {
                Id = c.Id,
                Name = c.Name,
                ImageUrl = c.ImageUrl,
                ZipCode = c.ZipCode,
                Carriers = _carrierService.GetByCity(c),
                BusStations = _busStationService.GetByCity(c.Id)
            });

            var model = new CityIndexModel
            {
                Cities = cityListing
            };

            return View(model);
        }


        public async Task<OpenWeatherResponseOutput> GetWeatherInfo(string city)
        {
            using (var client = new HttpClient()) {
                try
                {
                    client.BaseAddress = new Uri("https://api.openweathermap.org");
                    var response = await client.GetAsync($"/data/2.5/weather?q={city}&appid=437318050e913abb8509dc60a7d150f8&units=metric");
                    response.EnsureSuccessStatusCode();

                    var stringResult = await response.Content.ReadAsStringAsync();
                    var rawWeather = JsonConvert.DeserializeObject<OpenWeatherResponse>(stringResult);
                    return new OpenWeatherResponseOutput{ 
                        Temp = rawWeather.Main.Temp,
                        Summary = string.Join(",",rawWeather.Weather.Select(x=>x.Main)),
                        City=rawWeather.Name,
                        WindSpeed = rawWeather.Wind.Speed,
                        MaxTemp = rawWeather.Main.TempMax,
                        MinTemp = rawWeather.Main.TempMin,
                        Pressure = rawWeather.Main.Pressure
                    };
                }
                catch(HttpRequestException httpRequestException)
                {
                    return null;

                }
            }
               
        }

        public IActionResult GenTable()
        {
            PdfDocument document;

           document = new PdfDocument();
                PdfPage page = document.Pages.Add();

                PdfGraphics graphics = page.Graphics;

                PdfLightTable pdfLightTable = new PdfLightTable();

                pdfLightTable.DataSourceType = PdfLightTableDataSourceType.TableDirect;

                pdfLightTable.Columns.Add(new PdfColumn("Roll Number"));
                pdfLightTable.Columns.Add(new PdfColumn("Name"));
                pdfLightTable.Columns.Add(new PdfColumn("Class"));

                pdfLightTable.Rows.Add(new object[] { "111", "Luka", "III" });

                pdfLightTable.Draw(page, PointF.Empty);


           
            MemoryStream stream = new MemoryStream();
            document.Save(stream);

            stream.Position = 0;
            return File(stream,"application/pdf","test.pdf");
        }


        public IActionResult Detail(int id)
        {
            var city = _cityService.GetById(id);

            var model = new CityDetailModel
            {
                Id = city.Id,
                Name = city.Name,
                BusStations = _busStationService.GetByCity(id),
                Carriers = _carrierService.GetByCity(city),
                ImageUrl = city.ImageUrl,
                ZipCode = city.ZipCode
            };
            model.OpenWeather = GetWeatherInfo(model.Name);

            return View(model);
        }
    }
}

BusStationIS/Controllers/DepartureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusStationIS.Data.Models;
using BusStationIS.Data.ServiceSpecification;
using BusStationIS.Models.Departure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Shapes;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using PdfSharp.Pdf;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;

namespace BusStationIS.Controllers
{
    public class DepartureController : Controller
    {
        private readonly IDeparture _deparatureService;
        private readonly ICity _cityService;
        private readonly ICarrier _carrierService;
        private readonly IPaymentCategory _paymentCategoryService;
        private readonly IVehicle _vehicleService;
        private readonly IDistance _distanceService;
        private readonly IPriceManager _priceService;

        public DepartureController(IDeparture departureService,ICity cityService,ICarrier carrierService,IPaymentCategory paymentCategoryService,IVehicle vehicleService,IDistance distanceService,IPriceManager priceManager)
        {
            _deparatureService = departureService;
            _cityService = cityService;
            _carrierService = carrierService;
            _paymentCategoryService = paymentCategoryService;
            _vehicleService = vehicleService;
            _distanceService = distanceService;
            _priceService = priceManager;
        }

        public IActionResult Index()
        {
            var departures = _deparatureService.GetAll();

            var departuresListing = departures.Select(d => new DepartureDetailModel
            {
                Id = d.Id,
                Cards = d.Cards,
                NumberOfSeats = d.NumberOfSeats,
                Carrier = d.Carrier,
                CityFrom = d.CityFrom,
                CityTo = d.CityTo,
                Distance = d.Distance,
                PaymentCategory = d.PaymentCategory,
                PriceOfCard = d.PriceOfCard,
                Vehicle = d.Vehicle
            });

            var model = new DepartureIndexModel
            {
                Departures = departuresListing
            };


            return View(model);
        }


        public IActionResult Detail(int id)
        {
            var departure = _deparatureService.GetById(id);

            var model = new DepartureDetailModel
            {
                Id = departure.Id,
                NumberOfSeats = departure.NumberOfSeats,
                CityFrom = departure.CityFrom,
                CityTo = departure.CityTo,
                Carrier = departure.Carrier,
                Distance = departure.Distance,
                PaymentCategory = departure.PaymentCategory,
                PriceOfCard = departure.PriceOfCard,
                Vehicle = departure.Vehicle,
                Cards = departure.Cards
            };

            return View(model);
        }

        public IActionResult MakeSpecDeparture([Bind] SpecificallyDepartureIndex specificallyDeparture)
        {
            return View();
        }

        public IActionResult CreateSpecificallyDeparture()
        {
            var departures = _deparatureService.GetAll();

            var detailsDeparures = departures.Select(x => new SpecificallyDepartureDetail
            {
                Id = x.Id,
                Departure = x
            });

            var model = new SpecificallyDepartureIndex 
            { 
                Departures = _deparatureService.GetAll(),
                SpecificallyDepartureDetails = detailsDeparures
            };

            return View(model);
        }




        public IActionResult GenerateWord(int id)
        {
            Departure departure = _deparatureService.GetById(id);

            using (WordDocument document = new WordDocument())
            {
                document.EnsureMinimal();
                document.LastParagraph.AppendText("Hello Word");
                MemoryStream stream = new MemoryStream();

                document.Save(stream, FormatType.Docx);

                stream.Position = 0;

                return File(stream, "application/msword", "Result.docx");
            }
        }

        public IActionResult GeneratePdf()
        {
            PdfDocument document = new PdfDocument();
            document.Info.Title = "Created with PDFSharp";

            PdfPage page = document.AddPage();

            XGraphics grf = XGraphics.FromPdfPage(page);

            XFont font = new XFont("Verdana", 20, XFontStyle.BoldItalic);

            grf.DrawString("Hello World!", font, XBrushes.Black,
                new XRect(0, 0, page.Width, page.Height), XStringFormat.Center);
            
            MemoryStream stream = new MemoryStream();

            document.Save(stream, false);

            stream.Position = 0;

            return File(stream,"application/pdf","HelloPDF.pdf");
        }

        public IActionResult GenDocs()
        {
            DateTime now = DateTime.Now;
            string filename = "MixMigraDocAndPdfSharp.pdf";
            filename = Guid.NewGuid().ToString("D").ToUpper() + ".pdf";
            PdfDocument document = new PdfDocument();
            document.Info.Title = "PdfSharp XGraphic Sample";
            document.Info.Author = "Luka Radovanovic";
            document.Info.Subject = "Create with code snippets that show the use of graphical functions";
            document.Info.Keywords = "PDFsharp, XGraphics";

         //   SamplePage1(document);
            SamplePage2(document);

            MemoryStream stream = new MemoryStream();

            document.Save(stream, false);
            stream.Position = 0;
            return File(stream, "application/pdf", "HelloPDF.pdf");
        }

        public IActionResult GradientDocs()
        {
            var document = new PdfDocument();
            using (document = new PdfDocument())
            {
                var page = document.AddPage();
                var graphics = XGraphics.FromPdfPage(page, XGraphicsPdfPageOptions.Append);

                var bounds = new XRect(graphics.PageOrigin, graphics.PageSize);
                var state = graphics.Save();

                graphics.DrawRectangle(
                    new XLinearGradientBrush(bounds,
                    XColor.FromKnownColor(XKnownColor.Red),
                    XColor.FromKnownColor(XKnownColor.White),
                    XLinearGradientMode.ForwardDiagonal),bounds
                    );
                graphics.Restore(state);
                graphics.DrawString("Hello world",
                    new XFont("Arial", 20),
                    XBrushes.Black,
                    bounds.Center,
                    XStringFormat.Center);
                
                XPen pen = new XPen(XColors.DarkBlue, 2.5);
                graphics.DrawPie(pen, 10, 0, 100, 90, -120, 75);
                

                document.Save("test.pdf");
                document.Close();
            }
            MemoryStream stream = new MemoryStream();

            document.Save(stream, false);
            stream.Position = 0;
            return File(stream, "application/pdf", "test.pdf");
        }

        private void SamplePage2(PdfDocument document)
        {
            PdfPage page = document.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);

            gfx.MUH = PdfFontEncoding.Unicode;

            Document doc = new Document();

            MigraDoc.Rendering.DocumentRenderer docRender = new MigraDoc.Rendering.DocumentRenderer(doc);

            docRender.PrepareDocument();

            XRect A4Rect = new XRect(0, 0, XUnit.FromCentimeter(21).Point, XUnit.FromCentimeter(29.7).Point);

            int pageCount = docRender.FormattedDocument.PageCount;

            for(int idx = 0; idx < pageCount; idx++)
            {
                XRect rect = GetRect(idx);
                XGraphicsContainer container = gfx.BeginContainer(rect, A4Rect, XGraphicsUnit.Point);

                gfx.DrawRectangle(XPens.LightGray, A4Rect);

                docRender.RenderPage(gfx, idx + 1);

                gfx.EndContainer(container);
            }
            
        }



        public IActionResult TextAlignment()
        {
            const string text =
  "Facin exeraessisit la consenim iureet dignibh eu facilluptat vercil dunt autpat. " +
  "Ecte magna faccum dolor sequisc iliquat, quat, quipiss equipit accummy niate magna " +
  "facil iure eraesequis am velit, quat atis dolore dolent luptat nulla adio odipissectet " +
  "lan venis do essequatio conulla facillandrem zzriusci bla ad minim inis nim velit eugait " +
  "aut aut lor at ilit ut nulla ate te eugait alit augiamet ad magnim iurem il eu feuissi.\n" +
  "Guer sequis duis eu feugait luptat lum adiamet, si tate dolore mod eu facidunt adignisl in " +
  "henim dolorem nulla faccum vel inis dolutpatum iusto od min ex euis adio exer sed del " +
  "dolor ing enit veniamcon vullutat praestrud molenis ciduisim doloborem ipit nulla consequisi.\n" +
  "Nos adit pratetu eriurem delestie del ut lumsandreet nis exerilisit wis nos alit venit praestrud " +
  "dolor sum volore facidui blaor erillaortis ad ea augue corem dunt nis  iustinciduis euisi.\n" +
  "Ut ulputate volore min ut nulpute dolobor sequism olorperilit autatie modit wisl illuptat dolore " +
  "min ut in ute doloboreet ip ex et am dunt at.";

            PdfDocument document = new PdfDocument();

            PdfPage page = document.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);
            XFont font = new XFont("Times New Roman", 16, XFontStyle.Bold);
            XTextFormatter tf = new XTextFormatter(gfx);

            XRect xRect = new XRect(40,40,250,220);
            gfx.DrawRectangle(XBrushes.SeaShell, xRect);

BusStationIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BusStationIS</title>
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css”>
    <link rel=”stylesheet” href=”https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css”>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class=" mdl-js-layout mdl-layout--fixed-header">
        <header class="">
            <div id="main">
                <div class="container">
                    <nav>
                        <div class="nav-fostrap">
                            <ul>
                                <li>
                                    <a asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a asp-controller="City" asp-action="Index">City</a>
                                </li>
                                <li>
                                    <a asp-controller="Carrier" asp-action="Index">Carrier</a>
                                </li>
                                <li>
                                    <a asp-controller="Departure" asp-action="Index">Departure</a>
                                </li>
                                <li>
                                    <a asp-controller="Departure" asp-action="CreateSpecificallyDeparture">Create Specific Departure</a>
                                </li>
                            </ul>
                        </div>
                        <div class="nav-bg-fostrap">
                            <div class="navbar-fostrap"> <span></span> <span></span> <span></span> </div>
                            <a href="" class="title-mobile">Bus Station IS</a>
                        </div>
                    </nav>
                </div>

            </div>
        </header>
        <div class="content">

            @RenderBody()

        </div>

    </div>

    <footer>
        <div class="mui-container mui--text-center">
            Made with ♥ by &copy; 2020 - BusStationIS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src=”https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js”></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>